### PR TITLE
Use c# 9 features to reduce line count (30 lines)

### PR DESCRIPTION
**Pull request by CoenraadS**

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the submission.

I'm not primarily a C# developer, but is this still considered a recursive approach? Maybe you could rename the file to `recursive-cs9.cs` or something like that so the implementation type is glanceable. What do you think?

**Comment by CoenraadS** [comment]
It's not recursive, it's more like the foreach example (except using LINQ instead to save another line)

**Comment by nickjj** [comment]
Ah ok, maybe in that case you can rename it to `for-each-linq`? Because the existing recursive solution is also using linq.

**Comment by CoenraadS** [comment]
done

**Comment by nickjj** [comment]
Thanks!

**Pull request merged**
