### PR TITLE
Elixir random check.

### PR DESCRIPTION
**Pull request by BlindingDark**
Just for fun : ) 🙈

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @BlindingDark foe the solution! However, according to the README, we are looking for idiomatic solutions. If you are interested in renaming the functions and file to more precise names, we will gladly take it though!

**Comment by BlindingDark** [comment]
@josevalim 

> renaming the functions and file to more precise names

Ofcourse. 👌

**Comment by BlindingDark** [comment]
@josevalim I made some changes.
I think the code for correct checking is somewhat practical : )

**Comment by josevalim** [comment]
I understand it better now the solution is still using random positions instead of being idiomatic, so it is probably best to not merge it. Thank you!

**Pull request closed without merging**
