### PR TITLE
Racket solutions for benign mutation, algebraic effects, and auto-incrementing counters

### PR DESCRIPTION
**Pull request by gregr**

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for such an in depth series of solutions.

I know you put a lot of effort into it but would you be ok with removing the README file? Since it's directly associated with your implementations it could get confusing if another person submits a Racket solution.

**Comment by gregr** [comment]
Hi @nickjj .  Since these solutions are related, is it possible to use another subdirectory to keep them together, along with the README, in that case?

**Comment by nickjj** [comment]
Yeah we could do that, is there an overall arching theme to your solutions that you could use for your directory name? There's always using your name as a last resort but if there's a word or phrase to describe your solutions that would be ideal.

**Comment by gregr** [comment]
Maybe something simple like `benign-and-algebraic-effects` ?

**Comment by nickjj** [comment]
Sure.

**Comment by gregr** [comment]
@nickjj How is that?

**Comment by nickjj** [comment]
Looks good, thanks a lot.

**Comment by gregr** [comment]
Great, happy to contribute.

**Pull request merged**
