### PR TITLE
Create ForEachImmutable.java

### PR DESCRIPTION
**Pull request by renatoathaydes**
This solution uses a simple for-each loop, similar to the Python solution in the front page, but uses immutable records to hold the data.
Records are updated via `withX` methods (unfortunately, currently we need to write such methods by hand in Java 16, but in the future these methods might be automatically generated by the compiler).

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks a lot for the submission.

It looks like we have a Java for-each loop submission. Java is not my specialty, are there any distinct differences between your solution and https://github.com/josevalim/nested-data-structure-traversal/blob/master/java/ForEach.java?

**Comment by renatoathaydes** [comment]
yes, my solution uses immutable records rather than classes as in the existing solution.
Another solution also uses records, [StreamMap](https://github.com/josevalim/nested-data-structure-traversal/blob/master/java/StreamMap.java), but that solution uses the streams API and a helper `Index` class which in my opinion makes it much less straightforward compared to the other languages' solutions.

**Comment by nickjj** [comment]
Ok thanks, what do you think about renaming the file / class to `ForEachMutable`?

**Comment by renatoathaydes** [comment]
Sure. I admit the difference from the other solutions is small, but it might be still interesting to merge IMHO as it uses "good" stuff from other solutions in a unique way:

* immutable records used for representing the data.
* mutation done via copy (using `withX` methods in the records).
* usage of `OptionalInt` for the optional `position` field (instead of a nullable `Integer`).
* simple for loop combined with mutable List to collect results easily.

**Comment by nickjj** [comment]
Yeah that's fair. I know from personal experience that when it comes to implementing something, having more examples as a reference sometimes helps understand the problem better.

Thanks!

**Pull request merged**
