### PR TITLE
Lua implementation

### PR DESCRIPTION
**Pull request by IceDragon200**
I wasted way too much time on the json encoder...

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks for the solution.

Would it simplify things if you printed out the data structure directly without converting it to JSON? Most of the examples return back a dictionary or whatever data type resembles that for a specific language.

**Comment by IceDragon200** [comment]
@nickjj Stock lua can't print/inspect tables by itself, hence the mess that is the encoder below it, I apologize but it's that or: 
```
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> print({})
table: 0x55f6342e0f30
``` 

Code that prints the lua equivalent would still look like the code present (just replace ':' with '=' and unquote all the strings)

**Comment by nickjj** [comment]
Ah ok.

What do you think about creating a `lua/reduce/` directory and splitting out the json encoding code into a separate file? This way your implementation can be front and center in its own file.

**Comment by IceDragon200** [comment]
No problem, I'll happily extract it

**Comment by nickjj** [comment]
Looks good, thanks!

**Comment by stephannv** [comment]
Damn it. I was too slow haha.
https://github.com/stephannv/nested-data-structure-traversal/pull/1/files

**Comment by nickjj** [comment]
@stephannv you can open a PR for that. This implementation uses reduces but yours is using a for loop (or something that looks like one). More than happy to merge yours in.

**Comment by stephannv** [comment]
@nickjj this PR is using reduce just for show the final result, but the algorithm logic is identical, the difference is the iteration syntax. I use `for i = 1, #array do` and @IceDragon200 uses `for i in pairs(array)`.

**Pull request merged**
