### PR TITLE
Javascript for-of

### PR DESCRIPTION
**Pull request by jakub-gonet**
I think using reduce is less readable than simple for-each loops and since we don't have to operate on immutable objects we can modify them in place.

### CODE REVIEW

**Comment by nickjj** [comment]
Thank you for the submission! 👍

**Comment by josevalim** [comment]
Looks good, can you please rename the file to add the .js extension? Thank you!

**Comment by jakub-gonet** [comment]
Sorry! Should be all right now.

**Comment by nickjj** [comment]
Thanks a lot for the solution! 👍

**Pull request merged**
