### PR TITLE
add kotlin sample using foreach

### PR DESCRIPTION
**Pull request by shrikanthkr**

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @shrikanthkr ! Do you think it would be possible to keep the example in a single file? :) Or not so easy with kotlin?

**Comment by shrikanthkr** [comment]
@josevalim I can make it in a single file. It might not run as it needs a project structure similar to Java.

**Comment by josevalim** [comment]
@shrikanthkr it is ok if it doesn't fully run, as the goal is mostly to compare the approaches, and having the code is definitely clear enough!

**Comment by shrikanthkr** [comment]
@josevalim 👍 Pushed clearing out the extras

**Comment by nickjj** [comment]
Thanks a lot for the solution!

**Pull request merged**
