### PR TITLE
Add Clojure example

### PR DESCRIPTION
**Pull request by meox**
Adding a very simple Clojure implementation.
Warning: I'm not a Clojure expert

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks a lot for the solution.

I'm not a Clojure expert either. Does `nested` have a meaning here to describe your implementation?

**Comment by meox** [comment]
no it's a just a name for the file, we can find probably a better one

**Comment by nickjj** [comment]
What do you think about `reduce.clj` since you're using `reduce` a few times?

**Comment by nickjj** [comment]
Thanks a lot! 👍

**Pull request merged**
