### PR TITLE
Add Hoon solution

### PR DESCRIPTION
**Pull request by yosoyubik**
Thanks for setting this up!

I've assumed an urbit with a mounted desk and that both files are located inside the urbit directory, `nested.hoon` in the `gen` folder and `nested.json` in the `lib` folder.

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks a lot for the submission!

What do you think about inling the JSON into the `nested.hoon` file and changing the directory to `hoon/urbit/nested.hoon` or perhaps even `hoon/nested.hoon` if that makes sense?

**Comment by yosoyubik** [comment]
> inling the JSON into the nested.hoon

Well, that's a good question. I'm not sure that's possible, if we want to work with an actual json object (this line here: `/*  json-object  %json  /lib/nested/json` is saying "build this file for me as json") 

I could manually have the contents of the file inlined and structured as a hoon structure, but that would skip any json parsing...

**Comment by nickjj** [comment]
Skipping JSON parsing is totally fine. You can use Hoon's dictionary or dictionary-like object directly.

**Comment by yosoyubik** [comment]
Done!

**Comment by nickjj** [comment]
Excellent, thank you. Cool looking language!

**Comment by yosoyubik** [comment]
Awesome, thanks! :)

**Pull request merged**
