### PR TITLE
Apache Groovy (JVM language) simplest 'for each' solution

### PR DESCRIPTION
**Pull request by michalbcz**

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the submission.

Can you amend your commit to remove the `README.md` file?

**Comment by michalbcz** [comment]
Sure I can, but I added it for purpose. It's easier to be able to visit official language web without searching through google or other search engine.

**Comment by michalbcz** [comment]
README.md removed as requested

**Comment by nickjj** [comment]
Thanks.

Duly noted about the readme but it's one of those things where if we add it here then it should probably be added to every language's README. I think it's not too bad if folks end up Googling for a language if they wanted to learn more, especially since we have no call out or language TOC in the main repo's README. To find the link would require going to a specific language's directory on their own. I'm not sure how common that would be for someone to do. But thanks for thinking about the discovery of a language.

**Pull request merged**
