### PR TITLE
Add Elm solution

### PR DESCRIPTION
**Pull request by Janiczek**
Uses `indexedFoldl` and `indexedMap`; all data is immutable in Elm and all functions are pure.

When ran (`elm make Main.elm && open index.html`), produces:

elm

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! Can you please rename the file to something like `indexed.elm`? And there is no reason to commit the project file, so we can remove it. :)

**Comment by Janiczek** [comment]
If it's not planned to make this compilable (`elm.json` and the 3rd party `list-extra` dependency), then perhaps I can remove the `view*` stuff too and just dump the data structure with `Debug.toString` instead of something nice. Any thoughts on that?

**Comment by josevalim** [comment]
I think as is looks fine because people can extract the core part of they want to :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
