### PR TITLE
Add zig implementation using std.json.Value

### PR DESCRIPTION
**Pull request by daurnimator**
Run with e.g. `zig run jsonValue.zig`

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks for the submission.

Can you please rename the file from `jsonValue.zig` to `for.zig`?

**Comment by daurnimator** [comment]
> Can you please rename the file from `jsonValue.zig` to `for.zig`?

The approach take here is not really particular to for loops, but the semantics of the standard library's `json.Value`.
An alternate implementation might use something like

```zig
const InputLesson = struct {
    name: []const u8,
};

const InputSection = struct {
    title: []const u8,
    reset_lesson_position: bool,
    lessons: []const InputLesson,
};

const OutputLesson = struct {
    name: []const u8,
    position: u32,
};
const OutputSection = struct {
    title: []const u8,
    reset_lesson_position: bool,
    position: u32,
    lessons: []const OutputLesson,
};
```

which would be traversed differently.

**Comment by nickjj** [comment]
Ah ok, that makes sense.

Since you have an array of items from the json parser you loop over that because that's how you loop over an array I'm guessing?

**Comment by daurnimator** [comment]
> Since you have an array of items from the json parser you loop over that because that's how you loop over an array I'm guessing?

yes. also the fact that the json structures are mutable, so you *can* add an extra field of `position`; rather than making a new list.

**Pull request merged**
