### PR TITLE
Add Vim9 version.

### PR DESCRIPTION
**Pull request by airblade**
Here's a [Vim9](https://vimhelp.org/vim9.txt.html) version.

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks for the time to add this in but this is very similar to the current Vimscript implementation. If you want to take a shot at a completely different strategy feel free to open a new PR.

**Comment by airblade** [comment]
Actually it's an entirely new version of Vimscript – more or less a different language.

**Comment by nickjj** [comment]
Right but at its core the logic of the loop is the same.

**Comment by airblade** [comment]
True, apart from line 45 where you need to replace the section with a new one rather than update it in place, to get around Vim9's type checking.

**Pull request closed without merging**
