### PR TITLE
Add Julia solution using `foldl`

### PR DESCRIPTION
**Pull request by Pangoraw**
Hi! Here is a solution using Julia

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
Beautiful, thank you! For curiosity: I assume there is also a solution in Julia that is closer to the Python solution in the README?

**Comment by Pangoraw** [comment]
There is! One of the main difference is that you would need to specify that the counters are globals for writes.

```julia
section_counter = 1
lesson_counter = 1

for section in sections
  reset_lesson_position = section["reset_lesson_position"]

  if reset_lesson_position
    global lesson_counter = 1 # needs global otherwise it is ambiguous
  end

  section["position"] = section_counter
  global section_counter += 1 # needs global otherwise it is ambiguous

  for lesson in section["lessons"]
    lesson["position"] = lesson_counter
    global lesson_counter += 1 # needs global otherwise it is ambiguous
  end
end
```

**Comment by josevalim** [comment]
Thanks for sharing! And how global is global? Is it global based on the lexical scope or could it affect another global named `section_counter` in a completely separate file?

**Comment by Pangoraw** [comment]
`global` only affects the current `module` so it shouldn't be able to access variables from other files. However, it is possible to use `include("other_file.jl")` which will put the code in place (like php's include) so there will be variables from another file but run/instanciated only from the importing file. To modify a variable from another `module` it is required to `eval()` inside the said module to be explicit.

**Pull request merged**
