### PR TITLE
Add APL solution

### PR DESCRIPTION
**Pull request by Janiczek**
:upside_down_face: 

Uses [Partition `⊆`](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Partition.htm), [Partitioned Enclose `⊂`](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Partitioned%20Enclose.htm) and the trusty [Iota `⍳`](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Index%20Generator.htm).

If it is important to not change the first section's "reset" from False to True (it doesn't change the behaviour anyways), I can tweak the solution.

----

A layman's description of the algorithm:

I group the lesson lists together based on the reset fields (each new "reset" creates a new list):
```
[ [ section1Lessons, section2Lessons ], [ section3Lessons ] ]
```
Then I concatenate them together and generate the indexes
```
[ [1,2,3,4], [1,2] ]
```
Then I group it back according to the lessons
```
[ [1,2], [3,4], [1,2] ]
```
The rest is trivial, this is the only interesting part that's IMHO different from the rest of the solutions.

----

[Online REPL](https://tio.run/##RVDBSsNAEL3nK@a2CVhrP8BDbUUEe6oiIh42m7UMTHdDsikW8SJS2khFEcGzXnoXf6Cfsj9SJ6mkl2Xmvcd7b1am1Eqmkuxo418@elcil@QE@Ocn4H14vH/RG/RFbO/AGmjdHlojfPmtjYxJD7tn5xs0aeH87DUUJ9o5NCPIncycTgQcQCguNSk71gLEqWGCSDpkjyhi7kjmqMCmOpPOZlt9N0mwUkAbhkXsMqlqPYhBQQ5TQiX/6T5OMG@8uslEGqUTcDZFlQvoMDgonIyR0E2r/PF4t0ZRwOdxbT97qy8IDGRANfDul4sGVhW0@DJBdt254bkT5JhU2PJHBVSPYciC9YqiNlORL2d@XobM@/knE/zusVu0XmW@fKQAq5D7JsUvfx/Wq2ZlR6DAFm77qQ3OzlA1RNr13qo2mz8)

apl

### CODE REVIEW

**Comment by nickjj** [comment]
Hi, thanks for the solution.

Are REPL URLs immutable? Meaning, can a URL be the same even if you edit the code later?

Also thanks for the explanation haha. I wasn't sure if I was looking at alien hieroglyphics or slightly encrypted NES cheat codes.

**Comment by Janiczek** [comment]
No, the REPL URL encodes the source I believe. If I change the code, the URL also changes...

Re explanation, I can go over it in more detail but I figured this rough sketch gives most bang for the buck :)

**Comment by nickjj** [comment]
Ok cool, I only asked about the URL because I didn't want to run the risk of the URL changing in the future to be different content.

As for dropping in an explanation in the comment, it's up to you.

**Comment by nickjj** [comment]
Thanks a lot for adding this!

**Pull request merged**
